version: "3.9"

services:
    db:
        image: postgres:17
        env_file:
            - .env
        container_name: my_postgres
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data

    server:
        image: 221082170856.dkr.ecr.ap-northeast-1.amazonaws.com/web-project1/server:latest
        env_file:
            - .env
        restart: always
        ports:
            - "5000:5000"
        depends_on:
            - db

    client:
        image: 221082170856.dkr.ecr.ap-northeast-1.amazonaws.com/web-project1/client:latest
        env_file:
            - .env
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - server
        environment:
            - NODE_ENV: production
            - PORT: 3000

volumes:
    db_data:
