export const NOTIFICATION_RETENTION_DAYS = {
    SHORT: 60,
    NORMAL: 180,
    IMPORTANT: 365,
    PERMANENT: null,
} as const;

export const NOTIFICATION_TYPES = {
    LIKE: "LIKE",
    FOLLOW: "FOLLOW",
    ITEM: "ITEM",
    COMMENT: "COMMENT",
    COMMENT_REPLY: "COMMENT_REPLY",
    ORDER_CREATED: "ORDER_CREATED",
    ITEM_DELETED_BY_ADMIN: "ITEM_DELETED_BY_ADMIN",
    COMMENT_DELETED_BY_ADMIN: "COMMENT_DELETED_BY_ADMIN",
} as const;

export const NOTIFICATION_RETENTION_LEVEL = {
    [NOTIFICATION_TYPES.LIKE]: "SHORT",
    [NOTIFICATION_TYPES.FOLLOW]: "SHORT",
    [NOTIFICATION_TYPES.ITEM]: "NORMAL",
    [NOTIFICATION_TYPES.COMMENT]: "SHORT",
    [NOTIFICATION_TYPES.COMMENT_REPLY]: "SHORT",
    [NOTIFICATION_TYPES.ORDER_CREATED]: "IMPORTANT",
    [NOTIFICATION_TYPES.ITEM_DELETED_BY_ADMIN]: "PERMANENT",
    [NOTIFICATION_TYPES.COMMENT_DELETED_BY_ADMIN]: "IMPORTANT",
} as const;

export type NotificationRetentionLevel = keyof typeof NOTIFICATION_RETENTION_DAYS;
export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];
