name: Build & Push to ECR

on:
    push:
        branches: ["main"]

env:
    AWS_REGION: ap-northeast-1
    ECR_REGISTRY: 221082170856.dkr.ecr.ap-northeast-1.amazonaws.com
    CLIENT_REPO: web-project1/client
    SERVER_REPO: web-project1/server

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to ECR
              run: |
                  aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
                  docker login --username AWS --password-stdin $ECR_REGISTRY

            # =====================
            # CLIENT
            # =====================
            - name: Build & Push client
              run: |
                  docker build -t $ECR_REGISTRY/$CLIENT_REPO:latest ./client
                  docker build -t $ECR_REGISTRY/$CLIENT_REPO:${{ github.sha }} ./client
                  docker push $ECR_REGISTRY/$CLIENT_REPO:latest

            # =====================
            # SERVER
            # =====================
            - name: Build & Push server
              run: |
                  docker build -t $ECR_REGISTRY/$SERVER_REPO:latest ./server
                  docker build -t $ECR_REGISTRY/$SERVER_REPO:${{ github.sha }} ./server
                  docker push $ECR_REGISTRY/$SERVER_REPO:latest
